<b> Used for :
1. Image Classification
2. Regression
3. Reiforcement Learning
4. NLP

#installing

In [2]:
import tensorflow as tf
import numpy as np
print(tf.__version__)
print(np.__version__)


2.19.0
2.3.0


#creating tensors

In [3]:
string=tf.Variable("this is a string",tf.string)
number=tf.Variable(324,tf.int16)
floating=tf.Variable(3.567,tf.float64)

#rank/degree of tensors

In [4]:
rank1_tensor=tf.Variable(["Test","ok","Kim","moew"],tf.string)
rank2_tensor=tf.Variable([["test","ok","moew"],["test","yes","woof"],["ok","my","bad"]],tf.string)

to determine the rank of a tensor we can call the following method.

In [5]:
print(tf.rank(number))
print(tf.rank(rank1_tensor))
print(tf.rank(rank2_tensor))

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


In [6]:
rank2_tensor.shape


TensorShape([3, 3])

#changing shape

In [7]:
tensor1= tf.ones([1,2,3]) #tf.ones() creates a shape [1,2,3] tensor full of ones

tensor2= tf.reshape(tensor1,[2,3,1])#reshapes existing data to shape [2,3,1]
tensor3= tf.reshape(tensor2,[3,-1]) #-1 tells the tensor to calculate the size of the dimension in that place
                                    #this will reshape the tensor to [3,2]

#the no. of elements in the reshaped tensor must match the number in the original

In [8]:
print(tensor1)
print(tensor2)
print(tensor3)
#notice the changes in shape

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


#types of tensors
- variable
-constant
-placeholder
-sparseTensor

with the exception of <b>Variable</b> all the tensors are immuttable, meaning their value may not chnge during execution.
  

In [9]:
import tensorflow as tf
t=tf.zeros([5,5,5,5])
# print(t)
# t=tf.reshape(t,[625])
t=tf.reshape(t,[125,-1])
print(t)

tf.Tensor(
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]

#Tensorflow Core Learning Algorithms

* linear regression
* classification
* clustring
* hidden markov models

#Linear Regression